In [2]:
import pandas as pd

IMPUTE = True

if IMPUTE:
    df_train_features = pd.read_csv('task2_s92hdjw2/train_features.csv')
    df_train_labels = pd.read_csv('task2_s92hdjw2/train_labels.csv')
    df_test_features = pd.read_csv('task2_s92hdjw2/test_features.csv')
    
else:
    df_train_features = pd.read_csv('new_features.csv')
    df_train_labels = pd.read_csv('new_labels.csv')
    df_test_features = pd.read_csv('new_test_features.csv')

In [3]:
df_train_features.head()

,pid,Time,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,1,3,34.0,NaN,NaN,12.0,NaN,36.0,8.7,24.0,...,NaN,100.0,NaN,114.0,24.6,94.0,NaN,NaN,142.0,7.33
1,1,4,34.0,NaN,NaN,NaN,NaN,36.0,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,99.0,NaN,NaN,125.0,7.33
2,1,5,34.0,NaN,NaN,NaN,NaN,36.0,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,92.0,NaN,NaN,110.0,7.37
3,1,6,34.0,NaN,NaN,NaN,NaN,37.0,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,88.0,NaN,NaN,104.0,7.37
4,1,7,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100.0,NaN,NaN,22.4,81.0,NaN,NaN,100.0,7.41

In [4]:
df_train_labels.head()

,pid,LABEL_BaseExcess,LABEL_Fibrinogen,LABEL_AST,LABEL_Alkalinephos,LABEL_Bilirubin_total,LABEL_Lactate,LABEL_TroponinI,LABEL_SaO2,LABEL_Bilirubin_direct,LABEL_EtCO2,LABEL_Sepsis,LABEL_RRate,LABEL_ABPm,LABEL_SpO2,LABEL_Heartrate
0,1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,12.1,85.4,100.0,59.9
1,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.8,100.6,95.5,85.5
2,100,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,16.5,88.3,96.5,108.1
3,1000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,19.4,77.2,98.3,80.9
4,10000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.6,76.8,97.7,95.3

In [5]:
df_test_features.head()

,pid,Time,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,0,1,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,2,39.0,NaN,44.2,17.0,NaN,36.0,10.2,13.0,...,119.0,100.0,NaN,98.0,31.0,82.0,21.8,NaN,119.0,NaN
2,0,3,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,78.0,NaN,NaN,125.0,7.34
3,0,4,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,80.0,NaN,NaN,136.0,NaN
4,0,5,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,83.0,NaN,NaN,135.0,NaN

In [6]:
print(df_train_features.shape)
print(df_train_labels.shape)
print(df_test_features.shape)

(227940, 37)
(18995, 16)
(151968, 37)

In [7]:
# SUBTASKS
SUBTASK1 = ['BaseExcess', 'Fibrinogen', 'AST', 'Alkalinephos', 'Bilirubin_total',  'Lactate', 'TroponinI', 'SaO2', 'Bilirubin_direct', 'EtCO2']
SUBTASK2 = ['Sepsis']
SUBTASK3 = ['RRate', 'ABPm', 'SpO2', 'Heartrate']

# features that can be useful
columns = list(df_train_features.columns)
columns.remove('pid')
columns.remove('Time')

# Impute functinos

In [8]:
def get_defaults(features, labels, columns):
    """Default values for nans
    
    For subtask1's features nans: fill it with the average of all the corresponding negative-labeled features
    (e.g.) nans of 'AST' will be filled with the average of all the AST's negative-labeled features
    For subtask2's features nans: fill it with the same way as for subtask1's features
    For subtask3's features nans: fill it with (fill it with the values that the same-age(or closest) person has) or (the average)
                                                        In this function, default value is the average. The other method is defined in get_12rows function
    For other feartures nans: fill it with the average
    
    Args:
        features(df): 
        labels(df):
        columns(list): features' columns except 'pid' and 'TIme' since they cannot be nan
        
    Returns:
        defaults(dict): keys are column name, values are default values for that keys
    
    """
    import numpy as np
    defaults = dict()
    for column in columns:
        col_name = 'LABEL_' + column
        tmp = 0.
        print(column)
        if column in SUBTASK1:
            negative_labels_pids = labels.loc[labels[col_name] == 0.0, 'pid']
            denom = len(negative_labels_pids)
            for pid in negative_labels_pids:
                # if all are null don't count it
                if features.loc[features['pid'] == pid, column].isnull().all():
                    denom -= 1
                else:
                    tmp += features.loc[features['pid'] == pid, column].mean(skipna=True)
            defaults[column] = tmp / denom
            
        elif column in SUBTASK2:
            negative_labels_pids = labels.loc[labels[col_name] == 0.0, 'pid']
            denom = len(negative_labels_pids)
            for pid in negative_labels_pids:
                # if all are null don't count it
                if feature.loc[features['pid'] == pid, column].isnull().all():
                    denom -= 1
                else:
                    tmp += features.loc[features['pid'] == pid, column].mean(skipna=True)
            defaults[column] = tmp / denom
            
        elif column in SUBTASK3:
            defaults[column] = features[column].mean(skipna=True)
            
        else:
            defaults[column] = features[column].mean(skipna=True)
            
    return defaults

In [9]:
defaults = get_defaults(df_train_features, df_train_labels, columns)

Age
EtCO2
PTT
BUN
Lactate
Temp
Hgb
HCO3
BaseExcess
RRate
Fibrinogen
Phosphate
WBC
Creatinine
PaCO2
AST
FiO2
Platelets
SaO2
Glucose
ABPm
Magnesium
Potassium
ABPd
Calcium
Alkalinephos
SpO2
Bilirubin_direct
Chloride
Hct
Heartrate
Bilirubin_total
TroponinI
ABPs
pH

In [10]:
def get_12rows(features, rows, column, pid):
    """Get a person's data(12 x 1 dim data)
    
    fill nan.
    SUBTASK3's nans will be filled differently.
        first choice is to fill nans with the average of closest-aged  people's data
        second choice is to fill nans with defalut value got in get_defaults function
    
    Args:
        features(df): the whole dataframe
        rows(df): 12-rowed dataframe that has the same pid (pid, column)
        column: a feature
        pid(int): 
        
    Returns:
        rows(df): 12-rowed dataframe whose nans are filled in this function
        
    """
    import numpy as np
    
    if rows.any():
        rows.fillna(rows.mean(), inplace=True)

    else:
        if column in SUBTASK3:
            age = features.loc[features['pid']==pid, 'Age'].iat[0]
            min_age_distance = (features.loc[features['pid']!=pid, 'Age']- age).abs().min()
            df = df_train_features[df_train_features['pid']!=pid] # df_train features without current pid
            closest_age_pids =  df.loc[(df['Age']-age).abs() == min_age_distance, 'pid'].unique()# select indexes s.t. its ages are close
            default = features.loc[features['pid'].isin(closest_age_pids), 'RRate'].mean()
            rows.fillna(default, inplace=True)
            if not rows.any():
                rows.fillna(defaults[column], inplace=True)
            
        else:
            rows.fillna(defaults[column], inplace=True)
    
    return rows

In [11]:
def fill_nan(features, columns, pids):
    """imputing variable's strategy
    
    Args:
        features(df): the whole dataframe
        columns(list): features' columns except 'pid' and 'TIme' since they cannot be nan
        pids(list): pids. they are different from each other
        
    Returns:
        features(df): the whole dataframe whose nans are filled completly using 
    
    """
    for column in columns:
        print(column)
        for pid in pids:
            rows = features.loc[features['pid']==pid, column] # 12 data (for a person)
            features.loc[features['pid']==pid, column] = get_12rows(features, rows, column, pid)
    
    return features

# Train features set

In [ ]:
# fill nan 
pids = df_train_features['pid'].unique()
columns = list(df_train_features.columns)
columns.remove('pid')
columns.remove('Time')

df_train_features = fill_nan(df_train_features, columns,  pids)

In [ ]:
# visualize 
print(df_train_features.shape)
df_train_features.head()

In [ ]:
df_train_features.isna().sum(axis=0)

In [ ]:
# save new train features
df_train_features.to_csv('new_features.csv', index=False)

In [ ]:
df_train = pd.merge(df_train_features, df_train_labels, on='pid')

# Train labels set

In [ ]:
df = df_train_labels.copy()
df_train_labels = df_train_labels.append([df]*11)
df_train_labels = df_train_labels.sort_index()

In [ ]:
# visualize
print(df_train_labels.shape)
df_train_labels.head()

In [ ]:
# save new train features
df_train_labels.to_csv('new_labels.csv', index=False)

# Test features set

In [ ]:
# fill nan
all_test_pids = df_test_features['pid'].unique()
df_test_features = fill_nan(df_test_features, columns, all_test_pids)

In [ ]:
# visualize 
print(df_test_features.shape)
df_test_features.head()

In [ ]:
df_test_features.isna().sum(axis=0)

In [ ]:
# save new test features
df_test_features.to_csv('new_test_features.csv', index=False)

# Split train set into train val sets

In [8]:
import numpy as np

# split pids first
np.random.seed(0)
all_pids = df_train_features['pid'].unique()
np.random.shuffle(all_pids)
train_pids, val_pids = all_pids[:17000], all_pids[17000:]
print(all_pids.shape)
print(train_pids.shape)
print(val_pids.shape)

(18995,)
(17000,)
(1995,)

In [9]:
# split dataset
df_train_X = df_train_features[df_train_features['pid'].isin(train_pids)]
df_val_X = df_train_features[df_train_features['pid'].isin(val_pids)]

df_train_y = df_train_labels[df_train_labels['pid'].isin(train_pids)]
df_val_y = df_train_labels[df_train_labels['pid'].isin(val_pids)]

In [10]:
print(df_train_features.shape)
print(df_train_X.shape, df_train_y.shape)
print(df_val_X.shape, df_val_y.shape)

(227940, 37)
(204000, 37) (204000, 16)
(23940, 37) (23940, 16)

# Standardize features

In [11]:
from sklearn.preprocessing import StandardScaler

test_pids = df_test_features[['pid']]
# standardize train set, val set and test set with same mean and std as that of train set
scaler = StandardScaler().fit(df_train_X.loc[:, columns])
scaled_train_X = scaler.transform(df_train_X.loc[:, columns])
scaled_val_X = scaler.transform(df_val_X.loc[:, columns])
scaled_test_X = scaler.transform(df_test_features.loc[:, columns])

df_train_X = pd.DataFrame(scaled_train_X, columns=columns)
df_val_X = pd.DataFrame(scaled_val_X, columns=columns)
df_test_X = pd.DataFrame(scaled_test_X, columns=columns)
df_test_X = pd.concat([test_pids, df_test_X], axis=1)

In [12]:
print(df_train_X.shape)
df_train_X.head()

(204000, 35)

,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,BaseExcess,RRate,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,-1.704473,0.032728,0.034388,-0.650077,-0.120351,-1.046599,-1.131429,0.136420,-0.614944,-0.432564,...,-0.055708,0.634288,-0.030638,2.083929,-1.406615,0.549497,-0.099067,-0.070469,0.856463,-0.914284
1,-1.704473,0.032728,0.034388,-0.650077,-0.120351,-1.046599,-1.206092,0.624743,-0.614944,-0.432564,...,-0.055708,0.634288,-0.030638,1.555233,-1.678244,0.833729,-0.099067,-0.070469,0.106137,-0.914284
2,-1.704473,0.032728,0.034388,-0.650077,-0.120351,-1.046599,-1.206092,0.624743,0.266535,-0.026792,...,-0.055708,0.634288,-0.030638,1.555233,-1.678244,0.435804,-0.099067,-0.070469,-0.555915,-0.016316
3,-1.704473,0.032728,0.034388,-0.650077,-0.120351,0.299749,-1.206092,0.624743,0.266535,-0.026792,...,-0.055708,0.634288,-0.030638,1.555233,-1.678244,0.208418,-0.099067,-0.070469,-0.820736,-0.016316
4,-1.704473,0.032728,0.034388,-0.650077,-0.120351,-0.036838,-1.206092,0.624743,-0.027291,-0.026792,...,-0.055708,0.634288,-0.030638,1.555233,-1.833461,-0.189506,-0.099067,-0.070469,-0.997283,0.881652

In [13]:
print(df_val_X.shape)
df_val_X.head()

(23940, 35)

,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,BaseExcess,RRate,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,2.300291,-0.784081,0.034388,-1.003325,-0.120351,-0.373425,-0.627454,-0.05106,0.041968,0.176094,...,-0.055708,0.096934,-0.030638,0.037925,-0.669336,-0.405523,-0.099067,-0.070469,0.604883,-0.078466
1,2.300291,-0.784081,0.034388,-1.003325,-0.120351,-1.046599,-0.627454,-0.05106,0.041968,-0.026792,...,-0.055708,-0.645126,-0.030638,0.037925,-0.669336,-0.416892,-0.099067,-0.070469,-0.070410,-0.078466
2,2.300291,-0.784081,0.034388,-1.003325,-0.120351,-0.373425,-0.627454,-0.05106,0.041968,0.176094,...,-0.055708,0.096934,-0.030638,0.037925,-0.669336,-0.405523,-0.099067,-0.070469,0.604883,-0.078466
3,2.300291,-0.784081,0.034388,-1.003325,-0.120351,-0.373425,-0.627454,-0.05106,0.041968,-0.026792,...,-0.055708,0.634288,-0.030638,0.037925,-0.669336,-0.473739,-0.099067,-0.070469,-0.202820,-0.078466
4,2.300291,-0.784081,0.034388,-1.003325,-0.120351,-0.373425,-0.627454,-0.05106,0.041968,-0.229678,...,-0.055708,0.634288,-0.030638,0.037925,-0.669336,-0.587431,-0.099067,-0.070469,0.635779,-0.078466

In [14]:
print(df_test_X.shape)
df_test_X.head()

(151968, 36)

,pid,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,BaseExcess,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,0,-1.401082,0.032728,0.115827,-0.267391,-0.120351,-1.046599,-0.599456,-3.342885,-2.598273,...,0.46985,0.634288,-0.030638,-1.616943,-0.659635,0.009456,14.777131,-0.070469,0.266133,-0.016316
1,0,-1.401082,0.032728,0.300225,-0.355703,-0.120351,-1.046599,-0.291471,-3.892249,-2.598273,...,0.55711,0.634288,-0.030638,-2.145639,-0.164882,-0.132660,13.301147,-0.070469,-0.158684,-0.016316
2,0,-1.401082,0.032728,0.115827,-0.267391,-0.120351,-1.046599,-0.599456,-3.342885,-3.700122,...,0.46985,0.634288,-0.030638,-1.616943,-0.659635,-0.360046,14.777131,-0.070469,0.106137,-0.689792
3,0,-1.401082,0.032728,0.115827,-0.267391,-0.120351,-1.046599,-0.599456,-3.342885,-2.598273,...,0.46985,0.634288,-0.030638,-1.616943,-0.659635,-0.246353,14.777131,-0.070469,0.591642,-0.016316
4,0,-1.401082,0.032728,0.115827,-0.267391,-0.120351,-1.046599,-0.599456,-3.342885,-2.598273,...,0.46985,0.634288,-0.030638,-1.616943,-0.659635,-0.075814,14.777131,-0.070469,0.547506,-0.016316

# Training fuction

In [15]:
def model_fit(train_X, train_y, val_X, val_y, tasks, feature_selection, model):
    """
    
    Apply feature selection and training for each task.
    
    Args:
        X(df):
        y(df):
        feature_selection(func): 
        model(func):
        
    Returns:
        results(dict of dict): {task name: {hyper para11: score11, hyper para12: score12}, ..., {hyper para21: score21, }}
        transformers(dict): {task name: feature selection model, ... }
        
    """
    results = dict()
    models = dict()
    transformers = dict()
    for task in tasks:
        print(task)
        train_X_new, transformers[task] = feature_selection(train_X, train_y['LABEL_'+task])
        val_X_new = transformers[task].transform(val_X)
        results[task] = model(train_X_new, train_y['LABEL_'+task], val_X_new, val_y['LABEL_'+task])
    
    return results, transformers

# Subtask1

In [16]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression

def feature_selection1(X, y):
    """Feature selection for subtask1, subtask2
    
    Automatically select features by performing Linear Support vector machine on train dataset
        
    Args:
        X(df) : All the features
        y(Series) : The answers 
        
    Returns:
        X_new(df): selected features
        model: how to select features from its original (to perform the same feature selection method on test set)
    
    """
    #clf = LinearSVC(penalty='l1', C=10,  random_state=0, class_weight='balanced', dual=False).fit(X, y)
    clf = LogisticRegression(penalty='l1', solver='liblinear', C=5, random_state=0).fit(X, y)
    model = SelectFromModel(clf, prefit=True, max_features=5)
    X_new = model.transform(X)
    print(X_new.shape)
    
    return X_new, model

In [17]:
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn import metrics
from sklearn.metrics import roc_auc_score

def model1(train_X, train_y, val_X, val_y):
    """
    Train a model and evaluate it using ROC_AUC. 
    The activateion function is sigmoid. 
    
    Args:
        X(df) : Features that are useful for prediction
        y(Series) : The answers 
        
    Returns:
        scores(dict) : {task: score, ...}
    
    """
    clf = LinearSVC(random_state=0, class_weight='balanced', dual=False)
    #clf = LogisticRegression(random_state=0)
    
    C_s = [0.01, 0.1, 1, 5]
    
    scores = dict()
    for c in C_s:
        clf.C = c
        model = make_pipeline(PolynomialFeatures(degree=3), clf)
        model.fit(train_X, train_y)
        pred_y = model.predict(val_X)
        scores[c] = roc_auc_score(val_y, pred_y)
    
    return scores

In [18]:
#SUBTASK1 = ['BaseExcess', 'Fibrinogen', 'AST', 'Alkalinephos', 'Bilirubin_total',  'Lactate', 'TroponinI', 'SaO2', 'Bilirubin_direct', 'EtCO2']
subtask1_val_results,  subtask1_transformers = model_fit(df_train_X, df_train_y, df_val_X, df_val_y, 
                                                         SUBTASK1, feature_selection1, model1)
subtask1_val_results

BaseExcess
(204000, 5)
Fibrinogen
(204000, 5)
AST
(204000, 5)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

Alkalinephos
(204000, 5)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

Bilirubin_total
(204000, 5)
Lactate
(204000, 5)
TroponinI
(204000, 5)
SaO2
(204000, 5)
Bilirubin_direct
(204000, 5)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

EtCO2
(204000, 5)

{'BaseExcess': {0.01: 0.6984420409814958,
  0.1: 0.6966106231750521,
  1: 0.6995381860584888,
  5: 0.6995087772881307},
 'Fibrinogen': {0.01: 0.6645290430975584,
  0.1: 0.6645743575800671,
  1: 0.6645743575800671,
  5: 0.6645743575800671},
 'AST': {0.01: 0.6221321650765983,
  0.1: 0.6218718080260075,
  1: 0.6226170233403114,
  5: 0.6210695336626554},
 'Alkalinephos': {0.01: 0.6190805568093798,
  0.1: 0.6192559180500526,
  1: 0.6191819075959454,
  5: 0.6190178656011948},
 'Bilirubin_total': {0.01: 0.6231576224130382,
  0.1: 0.6233894194070934,
  1: 0.6235232868848039,
  5: 0.6231499663131606},
 'Lactate': {0.01: 0.6466005291005291,
  0.1: 0.646626984126984,
  1: 0.6459325396825396,
  5: 0.646626984126984},
 'TroponinI': {0.01: 0.6129518239349517,
  0.1: 0.6124873126008753,
  1: 0.6128356961014326,
  5: 0.6128356961014326},
 'SaO2': {0.01: 0.6683607284304923,
  0.1: 0.6682737416524825,
  1: 0.6672299003163656,
  5: 0.6672299003163656},
 'Bilirubin_direct': {0.01: 0.6044755546698551,
  0.1: 0.6047495682210708,
  1: 0.6041085425800453,
  5: 0.6040221867942075},
 'EtCO2': {0.01: 0.6951243586620887,
  0.1: 0.6941572774010722,
  1: 0.6940675752123389,
  5: 0.6941124263067056}}

In [20]:
# TODO: fill C
subtask1_models = dict()
#Cs = {'BaseExcess': 0.1, 'Fibrinogen': 0.1, 'AST': 0.1, 'Alkalinephos': , 'Bilirubin_total': ,  'Lactate': , 'TroponinI': , 'SaO2': , 'Bilirubin_direct': , 'EtCO2': }

for task in SUBTASK1:
    print(task)
    clf = LinearSVC(random_state=0, class_weight='balanced', dual=False)
    clf.C = 1 #Cs[task]
    model = make_pipeline(PolynomialFeatures(degree=4), clf)
    model.fit(subtask1_transformers[task].transform(df_train_X), df_train_y['LABEL_'+task])
    subtask1_models[task] = model

BaseExcess
Fibrinogen

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

AST

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

Alkalinephos

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

Bilirubin_total

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

Lactate
TroponinI

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

SaO2
Bilirubin_direct

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

EtCO2

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

# Subtask2

In [23]:
#SUBTASK2 = ['Sepsis']
subtask2_val_results, subtask2_transformers = model_fit(df_train_X, df_train_y, df_val_X, df_val_y, 
                                                        SUBTASK2, feature_selection1, model1)
subtask2_val_results

Sepsis
(204000, 5)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

{'Sepsis': {0.01: 0.5732481498612396,
  0.1: 0.5706300107924761,
  1: 0.5716128970089425,
  5: 0.5710289469626888}}

In [24]:
# TODO: fill C
subtask2_models = dict()

for task in SUBTASK2:
    print(task)
    clf = LinearSVC(random_state=0, class_weight='balanced', dual=False)
    clf.C = 1
    model = make_pipeline(PolynomialFeatures(degree=3), clf)
    model.fit(subtask2_transformers[task].transform(df_train_X), df_train_y['LABEL_'+task])
    subtask2_models[task] = model

Sepsis

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/svm/_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

# Subtask3

In [25]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import cross_val_score
from sklearn.feature_selection import SelectFromModel

def feature_selection3(X, y):
    """Feature selection for subtask3
    
    Automatically select features by performing Lasso(squared loss with l1 penalty) on train dataset
    
    Args:
        X(df): Features to make a prediction
        y(Series): The answers 
        
    Returns:
        X_new(df): selected features
        model: how to select features from its original (to perform the same feature selection method on test set)
        
    """
    lasso = Lasso(alpha=0.01).fit(X, y)
    model = SelectFromModel(lasso, prefit=True, max_features=5)
    X_new = model.transform(X)
    return X_new, model

In [26]:
from sklearn.linear_model import Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

def model3(train_X, train_y, val_X, val_y):
    """Model for subtask3
    
    Train a model and evaluate it using R2 score. 
    
    Args:
        X(df): Features to make a prediction
        y(Series): The answers 
        
    Returns:
        scores(dict): {task: score, ...}

    """
    reg = Ridge(random_state=0)
    alphas = [0, 0.01, 0.1, 1, 10]
    
    scores = dict()
    for alpha in alphas:
        reg.alpha = alpha
        model = make_pipeline(PolynomialFeatures(degree=4), reg)
        model.fit(train_X, train_y)
        pred_y = model.predict(val_X)
        scores[alpha] = r2_score(val_y, pred_y)
        
    return scores

In [ ]:
#SUBTASK3 = ['RRate', 'ABPm', 'SpO2', 'Heartrate']
subtask3_val_results, subtask3_transformers = model_fit(df_train_X, df_train_y, df_val_X, df_val_y, 
                                                        SUBTASK3, feature_selection3, model3)
subtask3_val_results

RRate

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=8.82685e-18): result may not be accurate.
  overwrite_a=True).T
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=8.82685e-17): result may not be accurate.
  overwrite_a=True).T

ABPm

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=8.91457e-18): result may not be accurate.
  overwrite_a=True).T
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/_ridge.py:148: LinAlgWarning: Ill-conditioned matrix (rcond=8.91457e-17): result may not be accurate.
  overwrite_a=True).T

SpO2

In [ ]:
subtask3_models = dict()
#alphas = {'RRate':, 'ABPm':, 'SpO2':, 'Heartrate':}

for task in SUBTASK3:
    print(task)
    reg = Ridge(random_state=0)
    reg.alpha = 1 #alphas[task]
    model = make_pipeline(PolynomialFeatures(degree=3), reg)
    model.fit(subtask3_transformers[task].transform(df_train_X), df_train_y['LABEL_'+task])
    subtask3_models[task] = lasso

# Helper functions

In [22]:
import numpy as np

def prediction(df, models, tasks, transformers):
    """Get results for predictions
    
    This function is to make predictions for given df with given models. 
    The results will be returned in a combined form of the predictions for all the tasks
    
    Args:
        df(df): df that you want to make predictions of
        models: models that are used to make predictions on
    
    Returns:
        df_total_result(df): Combined results
        
    TODO:
        perform the same feature selection
    
    """
    df_pid = df[['pid']].drop_duplicates(ignore_index=True)
    df_total_result = pd.DataFrame(data=df_pid.reindex(), columns=['pid'])
    df = df.drop(columns=['pid'])
    tmp_sum= 0
    
    for task in tasks:
        predictions = models[task].predict(transformers[task].transform(df))
        predictions = predictions.reshape(predictions.shape[0], 1)
   
        result_for_a_task = list()
        for i, prediction in enumerate(predictions):
            if i % 12 == 11:
                tmp_sum /= 12.
                result_for_a_task.append(tmp_sum)
                tmp_sum = 0
            tmp_sum += prediction
        else:
            if i % 12 != 11:
                tmp_sum /= (i % 12 + 1)
            print(f'done: {task}')
        
        record = pd.DataFrame(data=result_for_a_task , columns=['LABEL_' + task])
        df_total_result = pd.concat([df_total_result, record], axis=1)

    return df_total_result

In [ ]:
def output_to_csv(df, name):
    """Output df as csv
    
    Args:
        df(df): df that you want to output
        name(str): file name without its extension
    
    """
    file_name = name + '.zip'
    df.to_csv(file_name, index=False, float_format='%.3f', compression='zip')

# Prediction

In [ ]:
# prediction
tasks = list()
tasks.extend(SUBTASK1)
tasks.extend(SUBTASK2)
tasks.extend(SUBTASK3)
models = dict(subtask1_models.items() | subtask2_models.items() | subtask3_models.items())
transformers = dict(subtask1_transformers.items() | subtask2_transformers.items() | subtask3_transformers.items())
df_test_results = prediction(df_test_X,  models, tasks, transformers)

In [ ]:
# save result
output_to_csv(df_test_results, 'prediction')
df = pd.read_csv('prediction.zip')

In [ ]:
df.shape

In [ ]:
df = pd.read_csv('task2_s92hdjw2/sample.zip')

In [ ]:
df.shape